# Numpy

In [1]:
# Numpy is a general purpsoe array processig package. It provides high performance multidimensional array object and tools working with these arrays.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [9]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [10]:
type(my_lst)

list

In [11]:
type(arr)

numpy.ndarray

In [12]:
print(arr)

[1 2 3 4 5]


In [13]:
arr.shape     # will show only one value as one dimensional

(5,)

In [14]:
arr


array([1, 2, 3, 4, 5])

In [15]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array(my_lst1,my_lst2,my_lst3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [16]:
arr = np.array([my_lst1,my_lst2,my_lst3])

In [17]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [18]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
# [[ double bracket means two dimensional]]

In [20]:
arr.shape()

TypeError: 'tuple' object is not callable

In [21]:
arr.shape


(3, 5)

In [22]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [23]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [24]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [26]:
## Accessing the array elemenats

In [27]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
arr1[2]

3

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,1]
list3 = [2,3,4,5,6]

In [32]:
arr2 = np.array([list1,list2,list3])

In [33]:
arr2


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [34]:
arr2[:,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [35]:
arr2[1,3]

9

In [36]:
arr2[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [37]:
arr2[:,4:5]

array([[5],
       [1],
       [6]])

In [38]:
arr2[1:3,:]

array([[6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [39]:
arr2[1:4,:]

array([[6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [40]:
arr2[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [41]:
arr2[1:,:]

array([[6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [42]:
arr2[1:1,:]

array([], shape=(0, 5), dtype=int32)

In [43]:
arr2[0:1,:]

array([[1, 2, 3, 4, 5]])

In [44]:
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [45]:
arr2[:,0:2]

array([[1, 2],
       [6, 7],
       [2, 3]])

In [46]:
arr2[1:2,:]

array([[6, 7, 8, 9, 1]])

In [47]:
arr2[1:3,3:5]

array([[9, 1],
       [5, 6]])

In [48]:
arr2[1:2,1:4]

array([[7, 8, 9]])

In [49]:
array.arrange(0,10)

NameError: name 'array' is not defined

In [50]:
arr = np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [51]:
arr = np.arange(0,10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr = np.arange(0,10,step = 4)

In [54]:
arr

array([0, 4, 8])

In [55]:
 np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [56]:
arr = np.array(0,10)

TypeError: Cannot interpret '10' as a data type

In [57]:
arr = np.arange(0,10)

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr1[3:] = 100

In [60]:
arr1

array([  1,   2,   3, 100, 100])

In [61]:
arr[4:]=100

In [62]:
arr

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100])

In [63]:
arr[7:]=101.101

In [64]:
arr # float value will not be taken here

array([  0,   1,   2,   3, 100, 100, 100, 101, 101, 101])

In [65]:
arr

array([  0,   1,   2,   3, 100, 100, 100, 101, 101, 101])

In [66]:
arr3 = arr.copy()

In [67]:
arr3 [3:]=66
print(arr3)

[ 0  1  2 66 66 66 66 66 66 66]


In [68]:
arr

array([  0,   1,   2,   3, 100, 100, 100, 101, 101, 101])

In [69]:
## now main array value will not change as using copy function

In [70]:
val = 3
arr<val

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [71]:
## for 100 value ans will be false

In [72]:
arr3 * 2

array([  0,   2,   4, 132, 132, 132, 132, 132, 132, 132])

In [73]:
arr3[arr3<100]

array([ 0,  1,  2, 66, 66, 66, 66, 66, 66, 66])

In [74]:
np.ones(4,dtype=float) ## by default float

array([1., 1., 1., 1.])

In [75]:
np.ones(4,dtype=int) ## by default float

array([1, 1, 1, 1])

In [76]:
np.ones((2,5),dtype=float) ## by default float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
np.random.rand(3,3)

array([[0.86353313, 0.19074663, 0.61172749],
       [0.35716426, 0.72525976, 0.95696013],
       [0.62026988, 0.55511816, 0.22794716]])

In [79]:
np.random.random_sample((1,5))

array([[0.43020279, 0.36410311, 0.0506331 , 0.76920299, 0.63046948]])

In [81]:
np.random.randint(0,100,8)

array([97, 89, 41, 29, 56, 49, 88, 91])